---
title: "lab3"
format: html
---

remotes::install_github("lter/lterdatasampler")
```{r}
install.packages("tidyverse")
install.packages("flextable")
install.packages("zoo")
install.packages("dplyr")
remotes::install_github("lter/lterdatasampler")
library(tidyverse)
library(flextable)
library(zoo)
library(dplyr)
library(readr)
```
```{r}
# Q1

# Q2

url <- "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"

my.date <- as.Date("2022-02-01")
my.state <- "Colorado"

colorado_data <- covid_data %>%
  filter(state == my.state)

colorado_daily <- colorado_data %>%
  group_by(county) %>%
  arrange(date) %>%
  mutate(
    new_cases = cases - lag(cases, default = 0),
    new_deaths = deaths - lag(deaths, default = 0)
  ) %>%
  ungroup()

cumulative_cases <- colorado_data %>%
  group_by(county) %>%
  arrange(date) %>%
  mutate(cumulative_cases = cumsum(cases)) %>%
  ungroup()

```
```{r}
#Q2

new_cases_on_date <- colorado_daily %>%
  filter(date == my.date) %>%
  arrange(desc(new_cases)) %>%
  head(5) %>%
 

print(new_cases_on_date)

cumulative_cases <- colorado_data %>%
  group_by(county) %>%
  arrange(date) %>%
  mutate(cumulative_cases = cumsum(cases)) %>%
  ungroup()

colorado_daily <- colorado_data %>%
  group_by(county) %>%
  arrange(date) %>%
  mutate(
    new_cases = cases - lag(cases, default = 0),
    new_deaths = deaths - lag(deaths, default = 0)
  ) %>%
  ungroup()

cumulative_cases_on_date <- cumulative_cases %>%
  filter(date == my.date) %>%
  arrange(desc(cumulative_cases)) %>%
  head(5) %>%
  

print(cumulative_cases_on_date)

new_cases_on_date <- colorado_daily %>%
  filter(date == my.date) %>%
  arrange(desc(new_cases)) %>%
  head(5)

cumulative_cases_on_date <- cumulative_cases %>%
  filter(date == my.date) %>%
  arrange(desc(cumulative_cases)) %>%
  head(5)

print(new_cases_on_date)
print(cumulative_cases_on_date)

```
```{r}
#Q3
library(tidyverse)
library(readr)

pop_url <- 'https://www2.census.gov/programs-surveys/popest/datasets/2020-2023/counties/totals/co-est2023-alldata.csv'
population_data <- read_csv(pop_url)

population_data <- population_data %>%
  mutate(
    STATE = as.numeric(STATE),
    COUNTY = as.numeric(COUNTY),
    STATE = sprintf("%02d", STATE),
    COUNTY = sprintf("%03d", COUNTY),
    FIPS = paste0(STATE, COUNTY)
  ) %>%
  filter(COUNTY != "000") %>%
  select(FIPS, contains("NAME"), contains("2021"))

print(names(population_data))
print(dim(population_data))
print(nrow(population_data))
str(population_data)
glimpse(population_data)
range(population_data$POPESTIMATE2021)

# The data from the census website has many more columns, and contains things like birth/death rates, along with population estimates and changes, among other things.

covid_with_pop <- colorado_daily %>%
  left_join(population_data, by = c("fips" = "FIPS")) %>%
  left_join(cumulative_cases, by = c("date", "county", "state", "fips"))

covid_with_pop <- covid_with_pop %>%
  mutate(
    per_capita_cumulative_cases = cumulative_cases.y / POPESTIMATE2021,
    per_capita_new_cases = new_cases.x / POPESTIMATE2021,
    per_capita_new_deaths = new_deaths / POPESTIMATE2021
  )

date_2021 <- as.Date("2021-01-01")

top_cumulative_per_capita <- covid_with_pop %>%
  filter(date == date_2021) %>%
  arrange(desc(per_capita_cumulative_cases)) %>%
  head(5) %>%
  select(county, date, per_capita_cumulative_cases)

print(top_cumulative_per_capita)

top_new_per_capita <- covid_with_pop %>%
  filter(date == date_2021) %>%
  arrange(desc(per_capita_new_cases)) %>%
  head(5) %>%
  select(county, date, per_capita_new_cases)

print(top_new_per_capita)

```
```{r}
#Q4
```
```{r}
#Q5
```
```{r}
#Q6
```
```{r}
#Q7
```
```{r}
#Q8
```